name: ITskolarSystem-Homepage CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: /srv/ITskolar-System
    steps:
    - name: Pull Repository
      run: git submodule update --remote itskolarngbayan.xyz
    - name: Build Container
      run: docker compose build homepage-builder
    - name: Start Containers and push to nginx
      run: docker compose up -d homepage-builder
